version: '3'

services:
  # MongoDB - база данных для хранения информации о пользователях, ключах и т.д.
  mongodb:
    image: mongo:4.4
    container_name: zalupaspb-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - "27017:27017"
    networks:
      - zalupaspb-network

  # Веб-приложение
  webapp:
    build: 
      context: ./webapp
    container_name: zalupaspb-webapp
    restart: always
    depends_on:
      - mongodb
    ports:
      - "${WEB_PORT}:3000"
    environment:
      MONGO_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/zalupaspb?authSource=admin"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "production"
      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
      DISCORD_REDIRECT_URI: "${DISCORD_REDIRECT_URI}"
    networks:
      - zalupaspb-network

  # Discord бот
  discord-bot:
    build:
      context: ./discord-bot
    container_name: zalupaspb-discord-bot
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/zalupaspb?authSource=admin"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"
      DISCORD_LOG_CHANNEL_ID: "${DISCORD_LOG_CHANNEL_ID}"
      DISCORD_USER_ROLE_ID: "${DISCORD_USER_ROLE_ID}"
      DISCORD_MOD_ROLE_ID: "${DISCORD_MOD_ROLE_ID}"
      DISCORD_ADMIN_ROLE_ID: "${DISCORD_ADMIN_ROLE_ID}"
    networks:
      - zalupaspb-network

networks:
  zalupaspb-network:
    driver: bridge

volumes:
  mongodb_data: 